snakefile: Snakefile
latency-wait: 300
show-failed-logs: True
printshellcmds: True
rerun-incomplete: True
keep-going: True

until: MACS2
notemp: True
jobs: 25
executor: slurm

default-resources:
  slurm_extra: "'--qos=priority'"
  slurm_account: "team3"
  slurm_partition: "standard"
  mem_mb: 1000
  runtime: 60
