#!/bin/bash
#SBATCH -J STEP0
#SBATCH --cluster=nautilus
#SBATCH --qos=short
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu=10g
#SBATCH --time=10:00:00

# Commandes pour Obtain FastQC

# Définition du dossier de travail
projPath=$HOME/scratch/FastQC-data
SAMPLE="5-HV1GZMBi_S1_L001_R1_001"

# Création du dossier de sortie
mkdir -p $projPath/fastqFileQC/$SAMPLE



