#!/bin/bash
#SBATCH -J STEP0
#SBATCH --cluster=nautilus
#SBATCH --qos=short
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu=10g
#SBATCH --time=10:00:00

# ligne 1 - création du génome de référence
micromamba activate macs2
macs2 callpeak -t \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/HV_01_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/HV_01_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/HV_02_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/No_fixe_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/No_perm_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/No_perm_100K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/No_perm_50K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/No_perm_50K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/perm_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/perm_100K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/nautilus/users/iguerin2024@ec-nantes.fr/cutNtag/results/alignment/star/perm_50K_02.starAligned.sortedByCoord.out.bam \
-f BAMPE -g hs -n genome_reference_macs2

# ligne 2 - création de la matrice de compte 
# télécharger featureCounts
featureCounts -a genome_reference_macs2.gtf -o count_matrix.txt -p --countReadPairs \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/HV_01_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/HV_01_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/HV_02_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/No_fixe_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/No_perm_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/No_perm_100K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/No_perm_50K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/No_perm_50K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/perm_100K_01.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/perm_100K_02.starAligned.sortedByCoord.out.bam \
/home/iguerin2024@ec-nantes.fr/scratch/cutNtag/results/alignment/star/perm_50K_02.starAligned.sortedByCoord.out.bam \

# ligne 3 - génération de la heatmap avec le script python


