#!/bin/bash
#SBATCH -J STEP0
#SBATCH --cluster=nautilus
#SBATCH --qos=short
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu=10g
#SBATCH --time=10:00:00

# Initialisation de micromamba
eval "$(micromamba shell hook -s bash)"

# Activation de l'environnement fastqc  
micromamba activate fastqc

# Variables
projPath="$HOME/scratch/fastqFileQC"
DATA="/LAB-DATA/GLiCID/projects/CR2TI_lab/TEAM3/Projects/Proenc_CutNTag/CutTag/NS189_cutntag_240418"
SAMPLE="5-HV1GZMBi_S1_L001"

FASTQC_BIN="$HOME/micromamba/envs/fastqc/bin/fastqc"

# Dossiers
INPUT_DIR="$DATA/NS189_cutntag_240418"
OUT_DIR="$projPath/results/$SAMPLE"

# Création du dossier de sortie
mkdir -p "$OUT_DIR"

# Vérification
ls -ld "$OUT_DIR"

# Exécution FastQC
$FASTQC_BIN -o "$OUT_DIR" "$INPUT_DIR/${SAMPLE}_R1_001.fastq.gz"
$FASTQC_BIN -o "$OUT_DIR" "$INPUT_DIR/${SAMPLE}_R2_001.fastq.gz"
