#!/bin/bash
#SBATCH -J STEP1
#SBATCH --cluster=nautilus
#SBATCH --qos=short
#SBATCH --ntasks=1
#SBATCH --mem=2g
#SBATCH --qos=debug
#SBATCH --time=00:20:00 

# Accès vers python 
export PATH="$HOME/micromamba/envs/Trimmomatic/bin:$PATH"

# Activation de Trimmomatic 
TRIMMOMATIC_BIN="$HOME/micromamba/envs/Trimmomatic/bin/trimmomatic"


# Variables 
DATA="/LAB-DATA/GLiCID/projects/CR2TI_lab/TEAM3/Projects/Proenc_CutNTag/CutTag/NS189_cutntag_240418"
projPath="$HOME/scratch/fastqFileQC/results"
SAMPLE="5-HV1GZMBi_S1_L001"

# Création du dossier de sortie
OUT_DIR="$projPath/Trimming"
mkdir -p "$OUT_DIR"

$TRIMMOMATIC_BIN PE \
	"${DATA}/${SAMPLE}_R1_001.fastq.gz" \
	"${DATA}/${SAMPLE}_R2_001.fastq.gz" \
	"$OUT_DIR/${SAMPLE}_R1_001_paired.fastq.gz" \
	"$OUT_DIR/${SAMPLE}_R1_001_unpaired.fastq.gz" \
	"$OUT_DIR/${SAMPLE}_R2_001_paired.fastq.gz" \
	"$OUT_DIR/${SAMPLE}_R2_001_unpaired.fastq.gz" \
	ILLUMINACLIP:$HOME/micromamba/envs/Trimmomatic/share/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10:2:True\
	LEADING:3 TRAILING:3 MINLEN:22
