###########################
### Configuration Shell ###
###########################

# 1. On définit le chemin vers TON installation micromamba
MAMBA_ROOT = "/home/iguerin2024@ec-nantes.fr/micromamba"

# 2. On configure le shell pour Nautilus
shell.executable("/bin/bash")

# 3. Le préfixe magique : il définit la racine ET active le hook micromamba
shell.prefix(
    f"set -o pipefail; "
    f"export MAMBA_ROOT_PREFIX={MAMBA_ROOT}; "
    f"eval \"$({MAMBA_ROOT}/bin/micromamba shell hook -s bash)\"; "
)

# Chargement du fichier config
configfile: "config.json"
Snakedir = config["snakedir"]
Workdir = config["workdir"]
DataPath = config["DataPath"]
configfile: "config.json"


##################
###Load Modules###
##################
import pandas as pd

#####################
### Load functions ###
#####################

# 1. Liste simple des IDs d'échantillons
SAMPLES = list(config["samples"].keys())

# 2. LA FONCTION CRUCIALE : Elle traduit l'ID court en chemin long du serveur
def get_raw_fastq(wildcards):
    # Va chercher la valeur dans le config.json (ex: "NS133.../MonFichier")
    file_prefix = config["samples"][wildcards.sample]
    return {
        "r1": f"{DataPath}/{file_prefix}_R1_001.fastq.gz",
        "r2": f"{DataPath}/{file_prefix}_R2_001.fastq.gz"
    }

# 3. Liste pour MultiQC
def get_files_for_multiqc(wildcards):
    files = []
    for s in SAMPLES:
        files.append(f"{Workdir}/FastQC/fastqc_raw/{s}/{s}_R1_001_fastqc.zip")
        files.append(f"{Workdir}/FastQC/fastqc_raw/{s}/{s}_R2_001_fastqc.zip")
        files.append(f"{Workdir}/logs/trimmomatic/err_trimmomatic_{s}.txt")
    return files

##################
###target rules###
##################
rule all:
    input:
        # QC bruts
        expand(f"{Workdir}/FastQC/fastqc_raw/{{sample}}/{{sample}}_R1_001_fastqc.html", sample=SAMPLES),
        # Trimming
        expand(f"{Workdir}/Trimming/{{sample}}_R1_001_paired.fastq.gz", sample=SAMPLES),
        # Alignement (BAM final trié)
        expand(f"{Workdir}/alignment/star/{{sample}}.star.filter.sort.bam", sample=SAMPLES),
        # Stats d'alignement
        expand(f"{Workdir}/samstats/star/{{sample}}.star.stats", sample=SAMPLES)

##################
###import rules###
##################
include: "Rules/Preprocess/CutNTag_QC.smk"
