###########################
### Configuration Shell ###
###########################

# 1. Le dossier qui contient les environnements (fastqc, STAR, etc.)
MAMBA_ROOT_PREFIX = "/home/iguerin2024@ec-nantes.fr/micromamba"

# 2. Le chemin vers le programme micromamba 
MAMBA_EXE = "/home/iguerin2024@ec-nantes.fr/.local/bin/micromamba"

shell.executable("/bin/bash")
shell.prefix(
    f"set -o pipefail; "
    f"export MAMBA_ROOT_PREFIX={MAMBA_ROOT_PREFIX}; "
    f"eval \"$({MAMBA_EXE} shell hook -s bash)\"; "
)

# Chargement du fichier config
configfile: "config.json"
Snakedir = config["snakedir"]
Workdir = config["workdir"]
DataPath = config["DataPath"]
configfile: "config.json"


##################
###Load Modules###
##################
import pandas as pd

#####################
### Load functions ###
#####################

# 1. Liste simple des IDs d'échantillons
SAMPLES = list(config["samples"].keys())

# 2. LA FONCTION CRUCIALE : Elle traduit l'ID court en chemin long du serveur
def get_raw_fastq(wildcards):
    # Va chercher la valeur dans le config.json (ex: "NS133.../MonFichier")
    file_prefix = config["samples"][wildcards.sample]
    return {
        "r1": f"{DataPath}/{file_prefix}_R1_001.fastq.gz",
        "r2": f"{DataPath}/{file_prefix}_R2_001.fastq.gz"
    }

# 3. Liste pour MultiQC
def get_files_for_multiqc(wildcards):
    files = []
    for s in SAMPLES:
        files.append(f"{Workdir}/FastQC/fastqc_raw/{s}/{s}_R1_001_fastqc.zip")
        files.append(f"{Workdir}/FastQC/fastqc_raw/{s}/{s}_R2_001_fastqc.zip")
        files.append(f"{Workdir}/logs/trimmomatic/err_trimmomatic_{s}.txt")
    return files

##################
###target rules###
##################
rule all:
    input:
        # QC bruts
        expand(f"{Workdir}/FastQC/fastqc_raw/{{sample}}/{{sample}}_R1_001_fastqc.html", sample=SAMPLES),
        
        # QC après Trimming
        expand(f"{Workdir}/FastQC/fastqc_trimmed/{{sample}}/{{sample}}_R1_001_paired_fastqc.html", sample=SAMPLES),
        expand(f"{Workdir}/FastQC/fastqc_trimmed/{{sample}}/{{sample}}_R2_001_paired_fastqc.html", sample=SAMPLES),
        
        # Trimming
        expand(f"{Workdir}/Trimming/{{sample}}_R1_001_paired.fastq.gz", sample=SAMPLES),
        
        # Alignement (BAM final trié)
        expand(f"{Workdir}/alignment/star/{{sample}}.star.filter.sort.bam", sample=SAMPLES),
        
        # Stats d'alignement
        expand(f"{Workdir}/samstats/star/{{sample}}.star.stats", sample=SAMPLES),

        # bed et bigwig
        expand(f"{Workdir}/bigwig/{{sample}}.bw", sample=SAMPLES),
        f"{Workdir}/macs2/all_samples_peaks.narrowPeak",

        # nouvelles étapes deeptools
        f"{Workdir}/deeptools/matrix_peaks.gz",
        f"{Workdir}/deeptools/heatmap_peaks.png",

        # Deeptools MultiBamSummary
        f"{Workdir}/deeptools/multiBamSummary/multibamsummary_peaks.npz",
        f"{Workdir}/deeptools/multiBamSummary/multibamsummary_peaks.tab",

        # Deeptools plotPCA
        f"{Workdir}/deeptools/PCA/PCA_peaks.pdf",
        f"{Workdir}/deeptools/PCA/PCA_peaks.tab",

        # Deeptools plotProfile
        f"{Workdir}/deeptools/plotProfile/plotProfile_peaks.pdf",
        f"{Workdir}/deeptools/plotProfile/plotProfile_peaks.tab",

        # Homer
        f"{Workdir}/homer/peaks_annotation.txt",

        # MultiQC
        f"{Workdir}/multiQC/multiqc_report.html",

        # HOMER ET HEATMAP ANNOTÉE
        f"{Workdir}/deeptools/heatmap_annotated.png",  # Sortie de la heatmap groupée
        f"{Workdir}/homer/split_bed/promoters.bed",

        # extraire la liste des gènes 
        f"{Workdir}/homer/target_genes_list.tsv",

        # Find Motif Genome
        f"{Workdir}/homer/motifs"

##################
###import rules###
##################
include: "Rules/Preprocess/CutNTag_QC.smk"
